source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'mysql2','~>0.3.11'
gem 'json','~>1.7.6'
gem 'i18n','~>0.6.1'
gem 'sass-rails',   '~> 3.2.3'
gem 'therubyracer','~>0.12.0', :platforms => :ruby
gem 'sass-rails',   '~> 3.2.3'
gem 'coffee-rails', '~> 3.2.1'
gem 'jquery-rails','~>2.2.1'
gem 'jquery-ui-rails','~>4.0.2'
gem 'less','~>2.4.0'
gem 'less-rails','~>2.4.2'
gem 'twitter-bootstrap-rails','~>2.2.8'
gem 'haml','~>4.0.4'
gem 'simple_form','~>2.1.0'
gem 'execjs','~>1.4.0'
gem 'awesome_print','~>1.2.0'
gem 'uglifier', '~>2.2.1'
gem 'yui-compressor','~>0.12.0'
gem 'closure-compiler','~>1.1.10'
#Easy deployment in Amazon EC2
gem 'capistrano','~>2.14.2'
gem 'rvm-capistrano','~>1.2.7'
#ActiveModels has_secure_password
gem 'bcrypt-ruby', '~>3.0.1',:require => 'bcrypt'
#Authentication Framework
gem 'devise'
gem 'authlogic','~>3.2.0'
gem 'omniauth','~>1.1.4'
gem 'omniauth-facebook','~>1.4.1'
gem 'omniauth-twitter','~>1.0.0'
gem 'omniauth-linkedin','~>0.1.0'
gem 'omniauth-openid','~>1.0.1'
#Paginations
gem 'will_paginate', '~> 3.0'
#Search Utility
gem 'meta_search','~>1.1.3'
gem 'nokogiri','~>1.5.9'
gem 'rsolr','~>1.0.9'
gem 'rsolr-ext','~>1.0.3'
gem 'hash_struct','~>0.3'
gem 'ancestry','~>2.0.0'
gem 'hirb','~>0.7.1'
gem 'interactive_editor','~>0.0.10'
#Unicorn App server
gem 'unicorn','~>4.6.2'
gem 'faye','~>1.0.0'
gem 'private_pub','~>1.0.3'
# Server Required for Faye
gem 'thin','~>1.6.1'


#Passenger app server
gem 'passenger'


# Point systems
gem 'recognition'  #to test - no generators available
gem 'merit'

# fb friend/graph
gem 'fb_graph'

# nested has_many_through relation
gem 'nested_has_many_through'

gem 'api-versions'
gem 'rabl'

#create model-diagram
gem 'rails-erd'
